config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :donations
  resources :cases do 
    member do 
      get "accept"
      get "reject"
      get "manager"
      get "close"
      get "details"
      delete "unarchive"
    end
    get :autocomplete_problem_name, :on => :collection
    get :autocomplete_treatment_name, :on => :collection
    post :update_row_order, on: :collection

    resources :disbursments
    resources :requests
  end

  get '/reports' => 'welcome#index'

  devise_for :users, :skip => [:sessions]
  as :user do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :admins
  resources :users, controller: "users"
  resources :doctors

  post "/comments" => "comments#create"

  delete "/comments/:id" => "comments#destroy"

  get "/profile" => "users#profile"

  post "/caseReports" => "welcome#cases"
  post "/donationReports" => "welcome#donations"

  root 'cases#index'

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <h2>Error!</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="box-body">
    <div class="form-group">
      <label>First Name</label>
      <%= f.text_field :first_name, :class=> "form-control", :placeholder=>"First Name" %>
    </div>
    <div class="form-group">
      <label>Last Name</label>
      <%= f.text_field :last_name, :class=> "form-control", :placeholder=>"Last Name" %>
    </div>
    <div class="form-group">
      <label>Email address</label>
      <%= f.email_field :email, :class=> "form-control", :placeholder=>"Email" %>
    </div>
    <div class="form-group">
      <label>Password</label>
      <%= f.password_field :password, :class=> "form-control", :placeholder=>"Password" %>
    </div>
    <div class="form-group">
      <label>Mobile Number</label>
      <%= f.text_field :mobile_number, :class=> "form-control", :placeholder=>"Mobile Number" %>
    </div>
  </div><!-- /.box-body -->
  <%= f.hidden_field :role_cd, value: 0 %>
  <div class="box-footer">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Admins</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/admins">Admins</a></li>
    <li class="active">Edit Admin</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-6">
	    <!-- general form elements -->
	    <div class="box box-primary">
	      <div class="box-header with-border">
	        <h3 class="box-title">Edit Admin</h3>
	      </div><!-- /.box-header -->
	      <!-- form start -->

				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>			

<script>
  $("ul.sidebar-menu li").removeClass("active")
  $("ul.sidebar-menu li#admins").addClass("active")
</script>  

app/views/admins/index.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Admins</small>
  </h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Listing Admins</h3>
          <div class="box-tools">
            <div class="input-group">
              <%= link_to '<i class="fa fa-plus"></i> Add Admin'.html_safe, new_admin_path, class: "btn btn-success" %>
            </div>
          </div>
        </div><!-- /.box-header -->
        <br>

        <div class="box-body table-responsive no-padding">
          <table class="table table-hover table-bordered">
            <tbody><tr>
              <th>Email</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Mobile Number</th>
              <th>Actions</th>
            </tr>
            <%@admins.each do |user|%>
              <tr>
                <td><%=mail_to user.email %></td>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.mobile_number %></td>
                <td><%= link_to 'Show', user, class: "btn btn-xs btn-primary" %>
                <%= link_to 'Edit', edit_admin_path(user), class: "btn btn-xs btn-warning" %>
                <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>
              </tr>
            <%end%>
            <%if @admins.count < 1%>
            <tr>
              <td colspan="5" class="box-title"><h3>You don not have any admins yet. Add some</h3></td>
            </tr>
            <%end%>
          </tbody></table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div>
  </div>
</section>

<script>
  $("ul.sidebar-menu li").removeClass("active")
  $("ul.sidebar-menu li#admins").addClass("active")
</script>  

app/views/admins/new.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Admins</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/admins">Admins</a></li>
    <li class="active">Add Admin</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-6">
	    <!-- general form elements -->
	    <div class="box box-primary">
	      <div class="box-header with-border">
	        <h3 class="box-title">Add Admin</h3>
	      </div><!-- /.box-header -->
	      <!-- form start -->

				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>			

<script>
  $("ul.sidebar-menu li").removeClass("active")
  $("ul.sidebar-menu li#admins").addClass("active")
</script>  

app/views/admins/show.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Admin</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/admins">Admins</a></li>
    <li class="active">View Admin</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Admin Info</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <strong><i class="fa fa-envelope margin-r-5"></i>  Email</strong>
          <p class="text-muted">
            <%= @admin.email %>
          </p>

          <hr>

          <strong><i class="fa fa-user margin-r-5"></i> First Name</strong>
          <p class="text-muted"><%= @admin.first_name %></p>

          <hr>

          <strong><i class="fa fa-user margin-r-5"></i> Last Name</strong>
          <p class="text-muted"><%= @admin.last_name %></p>

          <hr>

          <strong><i class="fa fa-mobile margin-r-5"></i> Mobile Number</strong>
          <p class="text-muted"><%= @admin.mobile_number %></p>

        </div><!-- /.box-body -->
      </div>
    </div>
  </div>
</div>
<script>
  $("ul.sidebar-menu li").removeClass("active")
  $("ul.sidebar-menu li#admins").addClass("active")
</script>  