config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :donations
  resources :cases do 
    member do 
      get "accept"
      get "reject"
      get "manager"
      get "close"
      get "details"
      delete "unarchive"
    end
    get :autocomplete_problem_name, :on => :collection
    get :autocomplete_treatment_name, :on => :collection
    post :update_row_order, on: :collection

    resources :disbursments
    resources :requests
  end

  get '/reports' => 'welcome#index'

  devise_for :users, :skip => [:sessions]
  as :user do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :admins
  resources :users, controller: "users"
  resources :doctors

  post "/comments" => "comments#create"

  delete "/comments/:id" => "comments#destroy"

  get "/profile" => "users#profile"

  post "/caseReports" => "welcome#cases"
  post "/donationReports" => "welcome#donations"

  root 'cases#index'

end

app/models/disbursment.rb
class Disbursment < ActiveRecord::Base
  belongs_to :case
  belongs_to :user
  validates_presence_of :amount, :details

  has_attached_file :video
  validates_attachment_size :video, less_than: 100.megabytes
  validates_attachment_content_type :video, :content_type => ['video/quicktime', 'video/mp4', 'video/mpeg', 'video/mpeg4', 'video/x-flv', 'video/x-msvideo']

  after_save :set_recieve_amount

  def set_recieve_amount
  	self.case.recieved = self.case.disbursments.sum(:amount)
    self.case.remaining = self.case.budget.to_f - self.case.recieved.to_f
  	self.case.save
  end
end

app/controllers/disbursments_controller.rb
class DisbursmentsController < ApplicationController
  # before_action :set_case #, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :case
  load_and_authorize_resource :disbursment, :through => :case
  # GET /disbursments
  # GET /disbursments.json
  def index
    @disbursments = @case.disbursments
  end

  # GET /disbursments/1
  # GET /disbursments/1.json
  def show
  end

  # GET /disbursments/new
  def new
    @disbursment = Disbursment.new
  end

  # GET /disbursments/1/edit
  def edit
  end

  # POST /disbursments
  # POST /disbursments.json
  def create
    @disbursment = Disbursment.new(disbursment_params)
    @disbursment.case_id = @case.id
    respond_to do |format|
      if @disbursment.save
        format.html { redirect_to case_disbursment_path(@case, @disbursment), notice: 'Disbursment was successfully created.' }
        format.json { render :show, status: :created, location: @disbursment }
      else
        format.html { render :new }
        format.json { render json: @disbursment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disbursments/1
  # PATCH/PUT /disbursments/1.json
  def update
    respond_to do |format|
      if @disbursment.update(disbursment_params)
        format.html { redirect_to case_disbursment_path(@case, @disbursment), notice: 'Disbursment was successfully updated.' }
        format.json { render :show, status: :ok, location: @disbursment }
      else
        format.html { render :edit }
        format.json { render json: @disbursment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disbursments/1
  # DELETE /disbursments/1.json
  def destroy
    @disbursment.destroy
    respond_to do |format|
      format.html { redirect_to case_disbursments_url, notice: 'Disbursment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case
      @case = Case.find(params[:case_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disbursment_params
      params.require(:disbursment).permit(:amount, :details, :case_id, :video, :user_id)
    end
end

app/helpers/disbursments_helper.rb
module DisbursmentsHelper
end

app/views/disbursments/_form.html.erb
<%= form_for([@case, @disbursment]) do |f| %>
  <% if @disbursment.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <h2>Error!</h2>

      <ul>
      <% @disbursment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="box-body">
    <div class="form-group">
      <label>Amount</label>
      <%= f.text_field :amount, :class=> "form-control", :placeholder=>"Amount", style: "width: 20%" %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
    <hr>
    <h3>Case Files and Notes</h3>
    <hr>
    <div class="form-group">
      <label>Details</label>
      <%= f.cktext_area :details, :class=> "form-control" %>
    </div>
    <div class="form-group">
      <label>Upload Video</label>
      <%= f.file_field :video, :class=> "form-control" %>
    </div>
  </div><!-- /.box-body -->

  <div class="box-footer">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/disbursments/edit.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Disbursment</small>
  </h1>
  <ol class="breadcrumb">
  	<li><%= link_to "Cases", cases_path %></li>
    <li><%= link_to "Disbursments", case_disbursments_path %></li>
    <li class="active">Edit Disbursment</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-12">
	    <!-- general form elements -->
	    <div class="box box-primary">
	      <div class="box-header with-border">
	        <h3 class="box-title">Edit Disbursment</h3>
	      </div><!-- /.box-header -->
	      <!-- form start -->

				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>
<script>
  $("ul.sidebar-menu li").removeClass("active")
</script>  

app/views/disbursments/index.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Disbursment</small>
  </h1>

  <ol class="breadcrumb">
    <li><%= link_to "Cases", cases_path %></li>
    <li class="active">Disbursments</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Listing Disbursments For the Case</h3>
          <div class="box-tools">
            <div class="input-group">
              <%= link_to '<i class="fa fa-plus"></i> Add Disbursment'.html_safe, new_case_disbursment_path, class: "btn btn-success" %>
            </div>
          </div>
        </div><!-- /.box-header -->
        <br>

        <div class="box-body table-responsive no-padding"> 

          <table class="table table-hover table-bordered">
            <tbody><tr>
              <th>Amount</th>
              <th>Date of Disbursment</th>
              <th>Actions</th>
            </tr>
            <%@disbursments.each do |disbursement|%>
              <tr>
                <td><%= disbursement.amount %></td>
                <td><%= disbursement.created_at.strftime("%-d %b. %Y") %></td>
                <td><%= link_to 'Show', case_disbursment_path(@case, disbursement), class: "btn btn-xs btn-primary" %>
                <%= link_to 'Edit', edit_case_disbursment_path(@case, disbursement), class: "btn btn-xs btn-warning" %>
                <%= link_to 'Destroy', case_disbursment_path(@case, disbursement), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>
              </tr>
            <%end%>
            <%if @disbursments.count < 1%>
            <tr>
              <td colspan="5" class="box-title"><h3>You have not added any disbursements yet. Add some</h3></td>
            </tr>
            <%end%>
          </tbody></table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div>
  </div>
</section>
<script>
  $("ul.sidebar-menu li").removeClass("active")
</script>  

app/views/disbursments/new.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Disbursment</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "Disbursments", case_disbursments_path %></li>
    <li class="active">Add Disbursment</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-12">
	    <!-- general form elements -->
	    <div class="box box-primary">
	      <div class="box-header with-border">
	        <h3 class="box-title">Add Disbursment</h3>
	      </div><!-- /.box-header -->
	      <!-- form start -->

				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>

app/views/disbursments/show.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Disbursment</small>
  </h1>
  <ol class="breadcrumb">
  	<li><%= link_to "Cases", cases_path %></li>
    <li><%= link_to "Disbursments", case_disbursments_path %></li>
    <li class="active">Show Disbursment</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-12">
	    <!-- general form elements -->
	    <div class="box box-primary">
	      <div class="box-header with-border">
	        <h3 class="box-title">Show Disbursment</h3>
	      </div><!-- /.box-header -->
	      <!-- form start -->
	      <div class="box-body">
	      	<div class="form-group">
		      	<p>
						  <strong>Amount:</strong>
						  <%= @disbursment.amount %>
						</p>
		    	</div>
		    	<div class="form-group">
						<p>
						  <strong>Details:</strong>
						  <%= @disbursment.details.html_safe %>
						</p>
					</div>

					<div class="form-group">
						<p>
						  <strong>Video:</strong>
						  <%= videojs_rails source: @disbursment.video.url, setup: "{}", controls: true, width:"400", height: "200" %>
						</p>
					</div>	
				</div>
			</div>
		</div>
	</div>
</section>
<script>
  $("ul.sidebar-menu li").removeClass("active")
</script>  