config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :donations
  resources :cases do 
    member do 
      get "accept"
      get "reject"
      get "manager"
      get "close"
      get "details"
      delete "unarchive"
    end
    get :autocomplete_problem_name, :on => :collection
    get :autocomplete_treatment_name, :on => :collection
    post :update_row_order, on: :collection

    resources :disbursments
    resources :requests
  end

  get '/reports' => 'welcome#index'

  devise_for :users, :skip => [:sessions]
  as :user do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :admins
  resources :users, controller: "users"
  resources :doctors

  post "/comments" => "comments#create"

  delete "/comments/:id" => "comments#destroy"

  get "/profile" => "users#profile"

  post "/caseReports" => "welcome#cases"
  post "/donationReports" => "welcome#donations"

  root 'cases#index'

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :case
  validates_presence_of :content
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # before_action :set_requests
  # before_action :set_request, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :case
  load_and_authorize_resource :request, :through => :case

  # GET cases/1/requests
  def index
    @requests = @case.requests
  end

  # GET cases/1/requests/1
  def show
  end

  # GET cases/1/requests/new
  def new
    @request = @case.requests.build
  end

  # GET cases/1/requests/1/edit
  def edit
  end

  # POST cases/1/requests
  def create
    @request = @case.requests.build(request_params)

    if @request.save
      redirect_to([@request.case, @request], notice: 'Request was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT cases/1/requests/1
  def update
    if @request.update_attributes(request_params)
      redirect_to([@request.case, @request], notice: 'Request was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE cases/1/requests/1
  def destroy
    @request.destroy

    redirect_to case_requests_url(@case)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requests
      @case = Case.find(params[:case_id])
    end

    def set_request
      @request = @case.requests.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def request_params
      params.require(:request).permit(:content)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for([@request.case, @request]) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <h2>Error!</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="box-body">
    <div class="form-group">
      <label>Request Message</label>
      <%= f.text_area :content, :class=> "form-control", :placeholder=>"Request Message" %>
    </div>
  </div><!-- /.box-body -->
  <div class="box-footer">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Requests</small>
  </h1>
  <ol class="breadcrumb">
  	<li><%= link_to "Cases", cases_path %></li>
    <li><%= link_to 'Requests', case_requests_path(params[:case_id]) %></li>
    <li class="active">Edit Request</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-6">
	    <!-- general form elements -->
	    <div class="box box-primary">
	      <div class="box-header with-border">
	        <h3 class="box-title">Edit Request</h3>
	      </div><!-- /.box-header -->
	      <!-- form start -->

				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>			

<script>
  $("ul.sidebar-menu li").removeClass("active")
</script>  

app/views/requests/index.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Requests</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "Cases", cases_path %></li>
    <li class="active">Requests</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Listing Requests For this case</h3>
          <div class="box-tools">
            <div class="input-group">
              <%= link_to '<i class="fa fa-plus"></i> Add Request'.html_safe, new_case_request_path(params[:case_id]), class: "btn btn-success" %>
            </div>
          </div>
        </div><!-- /.box-header -->
        <br>

        <div class="box-body table-responsive no-padding">
          <table class="table table-hover table-bordered">
            <tbody><tr>
              <th>Content</th>
              <th>Actions</th>
            </tr>
            <%@requests.each do |request|%>
              <tr>
                <td><%= request.content %></td>
                <td><%= link_to 'Show', [request.case, request], class: "btn btn-xs btn-primary" %>
                <%= link_to 'Edit', edit_case_request_path(request.case, request), class: "btn btn-xs btn-warning" %>
                <%= link_to 'Destroy', [request.case, request], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>
              </tr>
            <%end%>
            <%if @requests.count < 1%>
            <tr>
              <td colspan="5" class="box-title"><h3>You don not have any requests yet. Add some</h3></td>
            </tr>
            <%end%>
          </tbody></table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div>
  </div>
</section>

<script>
  $("ul.sidebar-menu li").removeClass("active")
</script>  

app/views/requests/new.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Requests</small>
  </h1>
  <ol class="breadcrumb">
  	<li><%= link_to "Cases", cases_path %></li>
    <li><%= link_to 'Requests', case_requests_path(params[:case_id]) %></li>
    <li class="active">Add Request</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-6">
	    <!-- general form elements -->
	    <div class="box box-primary">
	      <div class="box-header with-border">
	        <h3 class="box-title">Add Request</h3>
	      </div><!-- /.box-header -->
	      <!-- form start -->

				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>			

<script>
  $("ul.sidebar-menu li").removeClass("active")
</script>  

app/views/requests/show.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Request</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "Cases", cases_path %></li>
    <li><%= link_to 'Requests', case_requests_path(params[:case_id]) %></li>
    <li class="active">View Requests</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Request Info</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <strong><i class="fa fa-envelope margin-r-5"></i>  Request Message</strong>
          <p class="text-muted">
            <%= @request.content %>
          </p>
        </div><!-- /.box-body -->
      </div>
    </div>
  </div>
</div>
<script>
  $("ul.sidebar-menu li").removeClass("active")
</script>  