config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :donations
  resources :cases do 
    member do 
      get "accept"
      get "reject"
      get "manager"
      get "close"
      get "details"
      delete "unarchive"
    end
    get :autocomplete_problem_name, :on => :collection
    get :autocomplete_treatment_name, :on => :collection
    post :update_row_order, on: :collection

    resources :disbursments
    resources :requests
  end

  get '/reports' => 'welcome#index'

  devise_for :users, :skip => [:sessions]
  as :user do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :admins
  resources :users, controller: "users"
  resources :doctors

  post "/comments" => "comments#create"

  delete "/comments/:id" => "comments#destroy"

  get "/profile" => "users#profile"

  post "/caseReports" => "welcome#cases"
  post "/donationReports" => "welcome#donations"

  root 'cases#index'

end

app/models/donation.rb
class Donation < ActiveRecord::Base
	validates_presence_of :amount
	before_create :set_month
	after_save :set_funds
	after_destroy :set_funds
	def set_month
		self.month = Date.today.strftime("%B %Y")
	end

	def set_funds
		f = Fund.find_or_create_by(id: 1)
		f.total_amount = Donation.all.sum(:amount)
		f.remaining_amount = f.remaining_amount.to_f + self.amount.to_f
		f.save
	end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # before_action :set_donation, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
    @cases = Case.all.where("recieved is Not ? and recieved > ?", nil, 0.0)
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:amount, :name, :city, :state, :country, :contact_number, :email, :comment)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
	def funds
		f = Fund.find(1)
		return f.remaining_amount if f.present?
		return 0
	end

	def afunds
		f = Fund.find(1)
		return f.total_amount if f.present?
		return 0
	end
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <h2>Error!</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="box-body">
    <div class="form-group">
      <label>Amount</label>
      <%= f.text_field :amount, :class=> "form-control", :placeholder=>"Amount" %>
    </div>
    <hr>
    <h3>Donor Information</h3>
    <hr>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, :class=> "form-control", :placeholder=>"Name" %>
    </div>
    <div class="form-group">
      <label>City</label>
      <%= f.text_field :city, :class=> "form-control", :placeholder=>"City" %>
    </div>
    <div class="form-group">
      <label>State</label>
      <%= f.text_field :state, :class=> "form-control", :placeholder=>"State" %>
    </div>
    <div class="form-group">
      <label>Country</label>
      <%= f.text_field :country, :class=> "form-control", :placeholder=>"Country" %>
    </div>
    <div class="form-group">
      <label>Contact Number</label>
      <%= f.text_field :contact_number, :class=> "form-control", :placeholder=>"Contact Number" %>
    </div>
    <div class="form-group">
      <label>Email</label>
      <%= f.email_field :email, :class=> "form-control", :placeholder=>"Email" %>
    </div>
    <div class="form-group">
      <label>Comment</label>
      <%= f.text_area :comment, :class=> "form-control", :placeholder=>"Comment" %>
    </div>
  </div><!-- /.box-body -->

  <div class="box-footer">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Donations</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/donations">Donations</a></li>
    <li class="active">Edit Donation</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-6">
	    <!-- general form elements -->
	    <div class="box box-primary">
	      <div class="box-header with-border">
	        <h3 class="box-title">Edit Donation</h3>
	      </div><!-- /.box-header -->
	      <!-- form start -->

				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>			

<script>
  $("ul.sidebar-menu li").removeClass("active")
  $("ul.sidebar-menu li#donations").addClass("active")
</script>  

app/views/donations/index.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Donations</small>
  </h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#incoming" data-toggle="tab">Incoming Donations</a></li>
          <li><a href="#outgoing" data-toggle="tab">Outgoing Donations</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="incoming">
            <div class="box-header">
              <h3>Funds Available: <b>Rs <%= funds %> </b></h3>
              <div class="box-tools">
                <div class="input-group">
                  <%= link_to '<i class="fa fa-plus"></i> Add Donation'.html_safe, new_donation_path, class: "btn btn-success" %>
                </div>
              </div>
            </div><!-- /.box-header -->
            <br>

            <div class="box-body table-responsive no-padding"> 

              <table class="table table-hover table-bordered">
                <tbody><tr>
                  <th>Amount</th>
                  <th>Name</th>
                  <th>City</th>
                  <th>State</th>
                  <th>Country</th>
                  <th>Contact number</th>
                  <th>Email</th>
                  <th>Actions</th>
                </tr>
                <%@donations.each do |donation|%>
                  <tr>
                    <td><%= donation.amount %></td>
                    <td><%= donation.name %></td>
                    <td><%= donation.city %></td>
                    <td><%= donation.state %></td>
                    <td><%= donation.country %></td>
                    <td><%= donation.contact_number %></td>
                    <td><%= donation.email %></td>
                    <td><%= link_to 'Show', donation, class: "btn btn-xs btn-primary" %>
                    <%= link_to 'Edit', edit_donation_path(donation), class: "btn btn-xs btn-warning" %>
                    <%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>
                  </tr>
                <%end%>
                <%if @donations.count < 1%>
                <tr>
                  <td colspan="8" class="box-title"><h3>You have not recieved any donations yet. Add some</h3></td>
                </tr>
                <%end%>
              </tbody></table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
          <div class="tab-pane" id="outgoing">
            <div class="box-header">
              <h3 class="box-title">Disbursement on Cases</h3>
            </div><!-- /.box-header -->
            <br>

            <div class="box-body table-responsive no-padding">
              <table class="table table-hover table-bordered">
                <tbody><tr>
                  <th>Treatment Cost</th>
                  <th>Patient Name</th>
                  <th>Amount Recieved</th>
                  <th>Users</th>
                  <th>Actions</th>
                </tr>
                <%@cases.each do |c|%>
                  <tr>
                    <td><%= c.budget %></td>
                    <td><%= c.name %></td>
                    <td><%= c.recieved.to_f %></td>
                    <td>
                      <% if c.users %>
                        <ul>
                          <% c.users.each do |u| %>
                            <li><%= u.try(:first_name) %>  <%= u.try(:last_name) %></li>
                          <% end %>
                        </ul>
                      <% else %>
                        <%= select_tag :user_id, options_for_select(User.all.collect{ |u| [u.first_name, u.id] }), {:prompt=>"Select a Manager", class: "form-control", 
                            data: {
                              remote: true,
                              url: manager_case_path(c)
                            }
                          }
                        %>
                      <% end %> 
                    </td>
                    <td><%= link_to 'Timeline', c, class: "btn btn-xs btn-primary" %></td>
                  </tr>
                <%end%>
                <%if @cases.count < 1%>
                <tr>
                  <td colspan="6" class="box-title"><h3>No outgoing funds yet</h3></td>
                </tr>
                <%end%>
              </tbody></table>
            </div><!-- /.box-body -->
          </div><!-- /.tab-pane -->
        </div><!-- /.tab-content -->
      </div>
    </div>
  </div>
</section>  

<script>
  $("ul.sidebar-menu li").removeClass("active")
  $("ul.sidebar-menu li#donations").addClass("active")
</script>  

app/views/donations/new.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Donations</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/donations">Donations</a></li>
    <li class="active">Add Donation</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-6">
	    <!-- general form elements -->
	    <div class="box box-primary">
	      <div class="box-header with-border">
	        <h3 class="box-title">Add Donation</h3>
	      </div><!-- /.box-header -->
	      <!-- form start -->

				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>			

<script>
  $("ul.sidebar-menu li").removeClass("active")
  $("ul.sidebar-menu li#donations").addClass("active")
</script>  

app/views/donations/show.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Donations</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/donations">Donations</a></li>
    <li class="active">View Donation</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Donation Info</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <strong><i class="fa fa-money margin-r-5"></i>  Amount</strong>
          <p class="text-muted">
            <%= @donation.amount %>
          </p>

          <hr>
          <h4><i class="fa fa-user margin-r-5"></i>  Donor Info</h4>
          <hr>

          <strong><i class="fa fa-user margin-r-5"></i> Name</strong>
          <p class="text-muted"><%= @donation.name %></p>

          <hr>

          <strong><i class="fa fa-envelope margin-r-5"></i> Email</strong>
          <p class="text-muted"><%= @donation.email %></p>

          <hr>

          <strong><i class="fa fa-mobile margin-r-5"></i> Contact Number</strong>
          <p class="text-muted"><%= @donation.contact_number %></p>


          <hr>

          <strong><i class="fa fa-map-marker margin-r-5"></i> Location</strong>
          <p class="text-muted"><%= @donation.city %>, <%= @donation.state %>, <%= @donation.country %></p>

        </div><!-- /.box-body -->
      </div>
    </div>
  </div>
</div>

<script>
  $("ul.sidebar-menu li").removeClass("active")
  $("ul.sidebar-menu li#donations").addClass("active")
</script>  